import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { attemptSync } from '@logosdx/utils';

const INDENT = '    ';

export const VALID_IDENT = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

export const jsonToInterface = (
    obj: Record<string, unknown>,
    depth: number
): string => {

    const prefix = INDENT.repeat(depth);
    let output = '';

    for (const key of Object.keys(obj)) {

        const value = obj[key];

        if (Array.isArray(value)) {

            console.warn(`Skipping array value at key "${key}"`);
            continue;
        }

        const safeKey = VALID_IDENT.test(key) ? key : `'${key}'`;

        if (typeof value === 'object' && value !== null) {

            output += `${prefix}${safeKey}: {\n`;
            output += jsonToInterface(value as Record<string, unknown>, depth + 1);
            output += `${prefix}};\n`;
        }
        else {

            output += `${prefix}${safeKey}: string;\n`;
        }
    }

    return output;
};

export interface ScanResult {
    rootShape: Record<string, unknown> | null;
    namespaces: Record<string, Record<string, unknown>>;
    codes: string[];
}

export const scanDirectory = (dir: string, locale: string): ScanResult => {

    const codes = new Set<string>();
    const namespaces: Record<string, Record<string, unknown>> = {};
    let rootShape: Record<string, unknown> | null = null;

    const entries = readdirSync(dir);

    if (entries.length === 0) {

        console.warn(`Warning: directory "${dir}" is empty`);
    }

    for (const entry of entries) {

        const fullPath = join(dir, entry);
        const stat = statSync(fullPath);

        if (stat.isFile() && entry.endsWith('.json')) {

            const code = entry.replace('.json', '');
            codes.add(code);

            if (code === locale) {

                const raw = readFileSync(fullPath, 'utf-8');
                const [parsed, err] = attemptSync(() => JSON.parse(raw));

                if (err) {

                    throw new Error(`Malformed JSON in ${fullPath}: ${err.message}`);
                }

                rootShape = parsed;
            }
        }
        else if (stat.isDirectory()) {

            const nsEntries = readdirSync(fullPath);

            for (const nsEntry of nsEntries) {

                if (!nsEntry.endsWith('.json')) continue;

                const code = nsEntry.replace('.json', '');
                codes.add(code);

                if (code === locale) {

                    const raw = readFileSync(join(fullPath, nsEntry), 'utf-8');
                    const [parsed, err] = attemptSync(() => JSON.parse(raw));

                    if (err) {

                        throw new Error(`Malformed JSON in ${join(fullPath, nsEntry)}: ${err.message}`);
                    }

                    namespaces[entry] = parsed;
                }
            }

            if (!namespaces[entry] && !nsEntries.some(e => e === `${locale}.json`)) {

                console.warn(`Warning: no "${locale}.json" found in "${entry}/", skipping namespace`);
            }
        }
    }

    return { rootShape, namespaces, codes: Array.from(codes) };
};

export const generateOutput = (
    scan: ScanResult,
    interfaceName: string
): string => {

    let output = '// Auto-generated by @logosdx/localize — do not edit\n\n';
    output += `import type { LocaleManager } from '@logosdx/localize';\n\n`;

    output += `export interface ${interfaceName} extends LocaleManager.LocaleType {\n`;

    if (scan.rootShape) {

        output += jsonToInterface(scan.rootShape, 1);
    }

    for (const ns of Object.keys(scan.namespaces).sort()) {

        output += `${INDENT}${ns}: {\n`;
        output += jsonToInterface(scan.namespaces[ns]!, 2);
        output += `${INDENT}};\n`;
    }

    output += '}\n\n';

    const sortedCodes = [...scan.codes].sort();
    const codeUnion = sortedCodes.length > 0
        ? sortedCodes.map(c => `'${c}'`).join(' | ')
        : 'never';
    output += `export type LocaleCodes = ${codeUnion};\n`;

    return output;
};
