// Auto-generated by @logosdx/localize — do not edit

import type { LocaleManager } from '@logosdx/localize';

export interface Locale extends LocaleManager.LocaleType {
    app: {
        title: string;
        subtitle: string;
    };
    todo: {
        placeholder: string;
        add: string;
        empty: string;
        status: {
            active: string;
            completed: string;
            deleted: string;
        };
        filters: {
            all: string;
            active: string;
            completed: string;
        };
        clear: string;
        remaining: string;
    };
    sync: {
        syncing: string;
        synced: string;
        error: string;
    };
    locale: {
        label: string;
    };
}

export type LocaleCodes = 'en' | 'es' | 'fr';
